#+AUTHOR: phdenzel
#+TITLE: Deep generative modelling for gravitational lensing fields from 3D models of galaxies
# Generating gravitational lensing deflection fields from 3D models of galaxies using deep learning for mock observations
#+DATE: 2023-04-26 Wed
#+OPTIONS: author:nil title:t date:nil timestamp:nil toc:nil num:nil \n:nil
#+LATEX_CLASS_OPTIONS: [a4paper,10pt]
#+LATEX_HEADER: \usepackage[margin=1.2in]{geometry}
#+LATEX_HEADER: \newgeometry{top=1in,bottom=1in,right=1.25in,left=1.25in}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \onehalfspacing
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \setlength{\droptitle}{-0.75in}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{makeidx}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{cleveref}
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{bm}

#+LATEX: \vspace{-0.8in}
** Project summary

Gravitational lensing is a phenomenon that occurs when rays of light
from a distant background source are deflected by the gravitational
field of a massive foreground object, e.g. a galaxy, which almost
perfectly aligns with the observer. While such occurrences are rare,
they are scientifically significant, because they provide the only
opportunity to directly infer the lensing galaxy's mass distribution,
including its dark matter content.  This unique perspective on a
galaxy's dark matter distribution offers exceptional insights into the
mysteries surrounding galaxy evolution, the nature of dark matter,
galaxy substructures, and even the expansion of the Universe. \\
Accurately predicting the deflection field of a strong gravitational
lens is a complex task that requires a detailed understanding of the
distribution of matter in the lensing galaxy. Conventional methods for
calculating these deflection fields, such as ray-tracing, are
computationally expensive, can take a long time to generate results,
and typically have to be fine-tuned by an experienced expert.

In recent years, deep learning methods have emerged as a promising
approach for generating and processing image-based data in various
scientific fields, often with super-human proficiency. These methods
employ neural networks to learn the mapping between the input
properties (for instance, the lensing galaxy) and the resulting image
(in this instance, the deflection field).

In this research proposal, I outline the usage of generative deep
learning methods to produce strongly lensing deflection fields of 3D
galaxy models from existing hydrodynamical simulation suites for the
purpose of creating mock observations, observational fits, and
corresponding source reconstructions. Specifically, I will explore
various state-of-the-art deep learning architectures, including
diffusion models, flow-based models, generative adversarial networks
(GANs), and variational autoencoders (VAEs) to develop a model that
can accurately generate the deflection field from a given 3D galaxy
model. The resulting deep learning model will be used to create
synthetic observations that can be compared to existing observational
data to test the accuracy of the lens model, and in particular
investigate the theoretical properties of the observed lensing
galaxies and their corresponding background source reconstructions,
within a Bayesian framework.

Lens modelling is inherently considered as a (degenerate) 2D inverse
problem. The novelty of this project consists of introducing 3D models
as direct input, which requires methods able to cover a broad range in
solution space due to the additional degeneracy introduced
thereby. Conventional modelling methods are insufficient due to the
typically low complexity of their models whereas deep learning methods
increase the model complexity with a high number of parameters, thus
able to span a wider range in solution space.

As of today, roughly 10^3 lenses have been discovered, only a fraction
of those properly analysed. Moreover, it is anticipated that the
next-generation satellites and telescopes such as
JWST\footnote{James~Webb~Space~Telescope}, Euclid,
SKA\footnote{Square~Kilometer~Array}, or
ELT\footnote{Extremely~Large~Telescope} may increase this number to
10^5. Thus, it is crucial to devise novel techniques that can scale
with big data efficiently.


#+LATEX: \newpage
** Project plan

*** State of research

Although gravitational lensing is often regarded as an optical
illusion that shows the same source in multiple images, lensing
systems possess distinct visual features which make them relatively
easy to spot by the trained eye. Nevertheless, wide-field surveys
capture billions of light sources, and over 100'000 strongly lensing
systems may still await discovery
[[citep:&Taak20;&Taak23;&Collett15]]. Not all these instances can be
examined by humans with the same level of scrutiny. \\
Deep learning methods have emerged as a promising approach for the
automated detection of strong gravitational lenses. In fact, recent
studies have demonstrated that deep learning techniques have led to a
significant increase in the number of identified strong lensing
candidates by more than threefold
[[citep:&Storfer22;&Huang21;&Rezaei22;&Wilde22]].

Contrary to the automated discovery of strong gravitational lenses
using deep learning, advancements for lens modelling have been more
restrained in that aspect. Still, the scientific community is actively
investigating how deep learning can be integrated into lens
modelling. \\
In a recent study by [[cite:&Gu22]], the same optimization methods
utilized in the backward propagation algorithm for training neural
networks were employed in a Bayesian framework. Through a Hamiltonian
Monte-Carlo sampling scheme, they obtained posterior estimates for
their lens model parameters, albeit with mediocre efficiency. Based on
the previous study, [[cite:&Mishra-Sharma22]] use continuous neural
fields to reconstruct strongly lensing sources from parametric lens
models. \\
Similarly, [[cite:&Morningstar19]] designed a custom recurrent neural
network (RNN) architecture, the recurrent inference machine (RIM), to
construct reconstructed source priors for fitting lens model
parameters. A subsequent study by [[cite:&Adam22]] incorporates the
lens modelling procedure in the RIM architecture. \\
In an automated pipeline setting, [[cite:&Schuldt22;&Chianese19]]
demonstrate that incorporating a simple CNN-based residual network
(ResNet) for estimating lens model parameters is comparable in
performance to traditional parametric lens modelling techniques. \\
Furthermore, [[cite:&Park20]] use a Bayesian neural network (BNN) to
characterize the posterior probabilities of lens model parameters for
the purpose of inferring the Hubble constant.

The very first gravitational lens discovered by [[cite:&Walsh79]] was
simultaneously confirmed and modelled by [[cite:&Young80]]. They used
a simple spherically symmetric lens model using 4 parameters to fit
the observation. Ever since then, even modern lens modelling tools (as
mentioned above) employ some type of parametric model (with typically
no more than 8 parameters) to fit the density distribution of the lens
[[citep:cf. &Birrer18;&Hezaveh17;&Tessore16;&Oguri10]]. Note that
[[cite:&Hezaveh17]] use convolutional neural networks (CNNs) to fit
mass distribution parameters to lens observations. However, this still
prescribes the same parametric constraints on the complexity of the
lensing galaxy's shape.

[[cite:&Young81]] already recognized that a major obstacle in lens
modelling is that numerous mass distributions could plausibly explain
observed data. This fact manifests as parameter degeneracies when
interpreting observations as discussed by
[[cite:&Saha00;&Saha06;&Schneider14;&Birrer21]].  An often ignored
issue with parametric models is that they assume to cover enough of
the solution space to encompass the "truth".  Congizant of this fact,
free-form lens modelling, as presented by [[citep:&Saha04]], uses an
over-parameterization trick to sample a wide range of solution
space. Despite this, the majority of fits are still not considered
realistic or physically viable.

All conventional lens modelling techniques rely on recipes which aim
to efficiently reproduce shapes and slopes of galaxies, as they are
usually observed. These methods therefore suppress or even completely
ignore the evolutionary processes of galaxies and the physical
properties which form and drive them. In contrast, cosmological
hydrodynamical simulations have made significant strides in recent
years, incorporating semi-analytical models which simulate star
formation and feedback effects at small scales, enabling exploration
of various galaxy-formation scenarios.

Integrating 3D galaxy models to lens modelling, doesn't alleviate the
already difficult computational and algorithmic challenge. However, it has been shown that deep learning
# Thus, I propose a data-driven approach to lens modelling that
# generates deflection fields from 3D galaxy models from hydrodynamical
# simulations and samples best-fitting solutions to observations from a
# latent feature space.

- in comes deep learning...
- deep learning architectures
- novelty distinguishing from the rest


*** Project description

- Goals
  
- Methods

Formally, the deflection field $\bm\alpha(\bm\theta, \xi)$ can be
expressed through a given angle on the observer's sky $\bm\theta$, and
a location and orientation of the 3D density $\rho(\bm\theta,z)$. The
convergence map (that is, the lensing mass distribution in
dimensionless form) is given by the usual projection of the 3D mass
density as

\begin{equation}
\label{eq:thinlens}
  \kappa(\bm\theta,\xi) = \frac{4\pi G}{cH_0}\, \frac{D_\mathrm{LS}D_\mathrm{L}}{D_\mathrm{S}} \int \rho(\bm\theta,\xi,z)\,\mathrm{d}z \,.
\end{equation}

Here, $D_{LS}$ is the dimensionless angular-diameter distance from the
lens to the source, $D_L$ and $D_S$ are analogous.  Finally, through
Poisson's equation we can connect the deflection field to the convergence as

\begin{equation}
  \alpha(\bm\theta,\xi) = \nabla_{\bm\theta}\psi(\bm\theta,\xi) = 2\nabla_{\bm\theta}^{-1}\kappa(\bm\theta,\xi) \,.
\end{equation}

  
- Approach
- Expected results
- Possible risks


*** Potential impact



# Bibliography ################################################################
# [[bibliographystyle:plainnat][Bibliography style]]
# [[bibliographystyle:unsrtnat][Bibliography style]]
[[bibliographystyle:apsrev][Bibliography style]]
[[bibliography:./gl3dgen.bib][Bibliography file]]
